spring:
  application:
    name: CMS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          course-service:
            connectTimeout: 5000
            readTimeout: 5000
    compatibility-verifier:
      enabled: false
server:
  port: 8087

cors:
  allowed-origins:
    - "http://localhost:5173"
    - "http://localhost:3000"
    - "https://effective-chunk-unwound.ngrok-free.dev"
    - "https://blah-hypnotist-tamper.ngrok-free.dev"
    - "https://paralyses-subfloor-overdraft.ngrok-free.dev"
    - "https://thinner-crudely-bunkmate.ngrok-free.dev"
    - "https://garage-army-vivacious.ngrok-free.dev"

aws:
  accessKey: ${AWS_ACCESS_KEY_ID:your_aws_access_key_here}
  secretKey: ${AWS_SECRET_ACCESS_KEY:your_aws_secret_key_here}
  region: ${AWS_REGION:ap-south-1}
  s3:
    bucket: ${AWS_S3_BUCKET:your_s3_bucket_name_here}
dynamodb:
  use-local: ${DYNAMODB_USE_LOCAL:false}
  endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}

jwt:
  secret: your_jwt_secret_key_here
version: 3
agent:
  authtoken: your_agent_token_here

course-ms:
  url: ${COURSE_MS_URL:http://localhost:8088}


resilience4j:
  circuitbreaker:
    instances:
      course-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        your_aws_secret_key_herebled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      course-service:
        maxAttempts: 3
        waitDuration: 1000
